package com.example.owlapi;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.sql.*;
import java.util.*;

/**
 * Scan relational schema and generate OBDA mapping files for GraphDB.
 * 
 * IMPORTANT: This generator is designed to produce OBDA mappings that are
 * COMPATIBLE with the OWL ontology generated by SchemaToOwlGenerator.
 * 
 * Key naming conventions (must match OWL generation):
 * - Class IRIs: baseIri + normalize(tableName)
 * - DataProperty IRIs: baseIri + normalize(tableName + "_" + columnName)  
 * - ObjectProperty IRIs: baseIri + normalize("ref_" + fkTable + "_to_" + pkTable)
 * 
 * This ensures SPARQL queries written against the OWL ontology will work
 * with the OBDA mappings.
 */
public class SchemaToObdaGenerator {

    private static final Logger logger = LoggerFactory.getLogger(SchemaToObdaGenerator.class);

    public static void main(String[] args) throws Exception {
        ObdaGeneratorArgs cfg = ObdaGeneratorArgs.fromArgs(args);
        generate(cfg);
        logger.info("OBDA generation completed.");
        logger.info("Output files:");
        logger.info("  - {}", cfg.output + ".obda");
        logger.info("  - {}", cfg.output + ".properties");
    }

    public static void generate(ObdaGeneratorArgs cfg) throws Exception {
        logger.info("Starting OBDA generation (OWL-compatible mode)...");
        logger.info("JDBC URL: {}", cfg.jdbcUrl);
        logger.info("Catalog: {}, Schema: {}, Table pattern: '{}'", cfg.catalog, cfg.schema, cfg.tablePattern);
        logger.info("Base IRI: {}", cfg.baseIri);

        Class.forName(cfg.driverClass);

        Map<String, TableInfo> tableInfoMap = new LinkedHashMap<>();

        try (Connection conn = DriverManager.getConnection(cfg.jdbcUrl, cfg.user, cfg.password)) {
            DatabaseMetaData meta = conn.getMetaData();
            String catalog = cfg.catalog != null ? cfg.catalog : conn.getCatalog();
            String schemaPattern = cfg.schema;
            String tablePattern = cfg.tablePattern == null || cfg.tablePattern.trim().isEmpty() ? "%" : cfg.tablePattern;

            // 1) Collect primary keys
            logger.info("Scanning primary keys...");
            Map<String, String> primaryKeys = new HashMap<>();
            try (ResultSet tables = meta.getTables(catalog, schemaPattern, tablePattern, new String[]{"TABLE"})) {
                while (tables.next()) {
                    String table = tables.getString("TABLE_NAME");
                    if (!acceptTable(table, cfg.includeTables, cfg.excludeTables)) continue;

                    try (ResultSet pks = meta.getPrimaryKeys(catalog, schemaPattern, table)) {
                        while (pks.next()) {
                            String pkColumn = pks.getString("COLUMN_NAME");
                            primaryKeys.put(table, pkColumn);
                            logger.debug("Table '{}' has primary key: {}", table, pkColumn);
                        }
                    }
                }
            }

            // 2) Collect columns for each table
            logger.info("Scanning columns...");
            try (ResultSet tables = meta.getTables(catalog, schemaPattern, tablePattern, new String[]{"TABLE"})) {
                while (tables.next()) {
                    String table = tables.getString("TABLE_NAME");
                    if (!acceptTable(table, cfg.includeTables, cfg.excludeTables)) continue;

                    TableInfo info = new TableInfo();
                    info.tableName = table;
                    info.primaryKey = primaryKeys.get(table);
                    
                    // Get the normalized class name (must match OWL generator)
                    info.classIri = cfg.baseIri + normalize(table);

                    try (ResultSet columns = meta.getColumns(catalog, schemaPattern, table, "%")) {
                        while (columns.next()) {
                            ColumnInfo col = new ColumnInfo();
                            col.columnName = columns.getString("COLUMN_NAME");
                            col.dataType = columns.getInt("DATA_TYPE");
                            col.typeName = columns.getString("TYPE_NAME");
                            col.nullable = columns.getInt("NULLABLE") == DatabaseMetaData.columnNullable;
                            
                            // Get the normalized property IRI (must match OWL generator)
                            col.propertyIri = cfg.baseIri + normalize(table + "_" + col.columnName);
                            
                            info.columns.add(col);
                            logger.debug("Table '{}' column: {} ({}) -> IRI: {}", 
                                table, col.columnName, col.typeName, col.propertyIri);
                        }
                    }

                    tableInfoMap.put(table, info);
                }
            }

            // 3) Collect foreign keys
            logger.info("Scanning foreign keys...");
            for (TableInfo info : tableInfoMap.values()) {
                try (ResultSet fks = meta.getImportedKeys(catalog, schemaPattern, info.tableName)) {
                    while (fks.next()) {
                        ForeignKeyRef fk = new ForeignKeyRef();
                        fk.fkColumn = fks.getString("FKCOLUMN_NAME");
                        fk.pkTable = fks.getString("PKTABLE_NAME");
                        fk.pkColumn = fks.getString("PKCOLUMN_NAME");
                        fk.fkName = fks.getString("FK_NAME");
                        
                        // Generate ObjectProperty IRI - MUST match OWL generator exactly!
                        // OWL format: ref_{fkTable}_to_{pkTable}_{fkName}
                        String opName = normalize("ref_" + info.tableName + "_to_" + fk.pkTable 
                            + "_" + (fk.fkName == null ? "fk" : fk.fkName));
                        fk.objectPropertyIri = cfg.baseIri + opName;
                        
                        // Get target class IRI
                        fk.targetClassIri = tableInfoMap.containsKey(fk.pkTable) 
                            ? tableInfoMap.get(fk.pkTable).classIri : null;
                        
                        info.foreignKeys.add(fk);
                        logger.debug("FK: {}.{} -> {}.{} -> OP: {}", 
                            info.tableName, fk.fkColumn, fk.pkTable, fk.pkColumn, fk.objectPropertyIri);
                    }
                }
            }
        }

        // 4) Generate OBDA file
        logger.info("Generating OBDA file...");
        String obdaContent = generateObdaContent(cfg, tableInfoMap);
        writeFile(cfg.output + ".obda", obdaContent);

        // 5) Generate properties file
        logger.info("Generating properties file...");
        String propsContent = generatePropertiesContent(cfg);
        writeFile(cfg.output + ".properties", propsContent);

        logger.info("Generation summary:");
        logger.info("  Tables processed: {}", tableInfoMap.size());
        logger.info("  Output: {}", cfg.output + ".obda");
        logger.info("  Output: {}", cfg.output + ".properties");
        
        // Print compatibility check info
        logger.info("");
        logger.info("=== SPARQL Compatibility Check ===");
        logger.info("The generated OBDA mappings use the SAME IRIs as the OWL ontology:");
        for (TableInfo info : tableInfoMap.values()) {
            logger.info("  Class: {}", info.classIri);
            for (ColumnInfo col : info.columns) {
                logger.info("    Property: {}", col.propertyIri);
            }
            for (ForeignKeyRef fk : info.foreignKeys) {
                if (fk.objectPropertyIri != null) {
                    logger.info("    ObjectProperty: {}", fk.objectPropertyIri);
                }
            }
        }
    }

    /**
     * Generate OBDA content with IRIs compatible with OWL generation.
     * 
     * Format uses SPARQL-BSEServies compatible syntax:
     * - Subject template: :ClassName/pkValue
     * - Predicate: :propertyName
     * - Object: literal values with xsd:type
     */
    private static String generateObdaContent(ObdaGeneratorArgs cfg, Map<String, TableInfo> tableInfoMap) {
        StringBuilder sb = new StringBuilder();

        // Prefix declarations - use same base as OWL
        sb.append("[PrefixDeclaration]\n");
        sb.append(":").append("\t").append(cfg.baseIri).append("\n");
        sb.append("g:").append("\t").append(cfg.baseIri).append("graph/\n");
        sb.append("owl:").append("\t").append("http://www.w3.org/2002/07/owl#\n");
        sb.append("rdf:").append("\t").append("http://www.w3.org/1999/02/22-rdf-syntax-ns#\n");
        sb.append("xml:").append("\t").append("http://www.w3.org/XML/1998/namespace\n");
        sb.append("xsd:").append("\t").append("http://www.w3.org/2001/XMLSchema#\n");
        sb.append("obda:").append("\t").append("https://w3id.org/obda/vocabulary#\n");
        sb.append("rdfs:").append("\t").append("http://www.w3.org/2000/01/rdf-schema#\n");
        sb.append("\n");

        // Mapping declarations
        sb.append("[MappingDeclaration] @collection [[\n\n");

        int mappingId = 1;

        for (TableInfo info : tableInfoMap.values()) {
            String tableName = normalize(info.tableName);
            String pkCol = info.primaryKey != null ? info.primaryKey : "id";
            
            // Subject template: :ClassName/{pk}
            String subjectTemplate = ":" + tableName + "/{" + pkCol + "}";

            // Mapping for table entity
            sb.append("mappingId\t").append("MAPPING-ID").append(mappingId++).append("\n");
            // target must be on single line or properly formatted
            sb.append("target\t\t").append(subjectTemplate).append(" a :").append(tableName).append(" .\n");

            // Add properties for each column (separate mapping)
            for (ColumnInfo col : info.columns) {
                // Skip the primary key column as it's already in the subject template
                if (col.columnName.equals(pkCol)) {
                    continue;
                }
                String xsdType = mapSqlTypeToXsd(col.dataType);
                sb.append("mappingId\t").append("MAPPING-ID").append(mappingId++).append("\n");
                sb.append("target\t\t").append(subjectTemplate)
                  .append(" :").append(normalize(info.tableName + "_" + col.columnName))
                  .append(" {").append(col.columnName).append("}^^xsd:").append(xsdType).append(" .\n");
                sb.append("source\t\tSELECT `").append(pkCol).append("`, `").append(col.columnName).append("` FROM `").append(info.tableName).append("`\n\n");
            }

            // Generate FK mappings for this table
            for (ForeignKeyRef fk : info.foreignKeys) {
                if (fk.targetClassIri == null) {
                    logger.warn("FK references unknown table '{}', skipping", fk.pkTable);
                    continue;
                }

                String targetTableName = normalize(fk.pkTable);
                
                // Subject: :ClassName/{pk}
                String fkSubjectTemplate = ":" + tableName + "/{" + pkCol + "}";
                // Object: :TargetClass/{fkValue}
                // IMPORTANT: the FK column value in the referencing table equals the referenced PK value.
                // So we must use fk.fkColumn as the placeholder (it exists in the source SELECT),
                // not fk.pkColumn (which is a column name in the referenced table).
                String fkObjectTemplate = ":" + targetTableName + "/{" + fk.fkColumn + "}";

                sb.append("mappingId\t").append("MAPPING-ID").append(mappingId++).append("\n");
                sb.append("target\t\t").append(fkSubjectTemplate)
                  .append(" :").append(fk.objectPropertyIri.substring(cfg.baseIri.length()))
                  .append(" ").append(fkObjectTemplate).append(" .\n");
                
                // Source query
                sb.append("source\t\tSELECT `").append(pkCol).append("`, `").append(fk.fkColumn).append("` FROM `").append(info.tableName).append("`\n\n");
            }
        }

        sb.append("]]\n");
        return sb.toString();
    }

    private static String generatePropertiesContent(ObdaGeneratorArgs cfg) {
        StringBuilder sb = new StringBuilder();

        String driverClass = cfg.driverClass;
        if (driverClass == null || driverClass.isEmpty()) {
            driverClass = "com.mysql.cj.jdbc.Driver";
        }

        sb.append("# OBDA Database Connection Configuration\n");
        sb.append("# Generated automatically - compatible with OWL ontology\n");
        sb.append("# Do not modify manually\n");
        sb.append("\n");
        sb.append("jdbc.driver=").append(driverClass).append("\n");
        sb.append("jdbc.url=").append(cfg.jdbcUrl).append("\n");
        sb.append("jdbc.username=").append(cfg.user).append("\n");
        sb.append("jdbc.password=").append(cfg.password).append("\n");

        return sb.toString();
    }

    /**
     * Map SQL type to XSD type - MUST match SchemaToOwlGenerator exactly!
     */
    private static String mapSqlTypeToXsd(int sqlType) {
        switch (sqlType) {
            case Types.INTEGER:
            case Types.SMALLINT:
            case Types.TINYINT:
                return "integer";
            case Types.BIGINT:
                return "long";
            case Types.FLOAT:
            case Types.REAL:
            case Types.DOUBLE:
                return "double";
            case Types.DECIMAL:
            case Types.NUMERIC:
                return "decimal";
            case Types.BOOLEAN:
            case Types.BIT:
                return "boolean";
            case Types.DATE:
                return "date";
            case Types.TIME:
                return "time";
            case Types.TIMESTAMP:
            case Types.TIMESTAMP_WITH_TIMEZONE:
                return "dateTime";
            default:
                return "string";
        }
    }

    /**
     * Normalize name - MUST match SchemaToOwlGenerator exactly!
     * Only keeps letters, numbers; replaces other chars with underscores.
     */
    private static String normalize(String raw) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < raw.length(); i++) {
            char c = raw.charAt(i);
            if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')) {
                sb.append(c);
            } else {
                sb.append('_');
            }
        }
        return sb.toString();
    }

    private static boolean acceptTable(String table, Set<String> include, Set<String> exclude) {
        String t = table == null ? "" : table.toLowerCase();
        if (exclude != null && exclude.contains(t)) return false;
        if (include == null || include.isEmpty()) return true;
        return include.contains(t);
    }

    private static void writeFile(String path, String content) throws IOException {
        File file = new File(path);
        File parent = file.getParentFile();
        if (parent != null) {
            parent.mkdirs();
        }

        try (FileWriter writer = new FileWriter(file)) {
            writer.write(content);
        }
        logger.info("Written: {}", file.getAbsolutePath());
    }

    // Inner classes for data structures
    private static class TableInfo {
        String tableName;
        String primaryKey;
        String classIri;  // The IRI of the OWL class (matches OWL generator)
        List<ColumnInfo> columns = new ArrayList<>();
        List<ForeignKeyRef> foreignKeys = new ArrayList<>();
    }

    private static class ColumnInfo {
        String columnName;
        int dataType;
        String typeName;
        boolean nullable;
        String propertyIri;  // The IRI of the OWL data property (matches OWL generator)
    }

    private static class ForeignKeyRef {
        String fkColumn;
        String pkTable;
        String pkColumn;
        String fkName;
        String objectPropertyIri;  // The IRI of the OWL object property (matches OWL generator)
        String targetClassIri;      // The IRI of the target class
    }
}
